// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: echo/v1/echo.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EcoServiceClient is the client API for EcoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcoServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type ecoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcoServiceClient(cc grpc.ClientConnInterface) EcoServiceClient {
	return &ecoServiceClient{cc}
}

func (c *ecoServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/echo.v1.EcoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcoServiceServer is the server API for EcoService service.
// All implementations must embed UnimplementedEcoServiceServer
// for forward compatibility
type EcoServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedEcoServiceServer()
}

// UnimplementedEcoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEcoServiceServer struct {
}

func (UnimplementedEcoServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEcoServiceServer) mustEmbedUnimplementedEcoServiceServer() {}

// UnsafeEcoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcoServiceServer will
// result in compilation errors.
type UnsafeEcoServiceServer interface {
	mustEmbedUnimplementedEcoServiceServer()
}

func RegisterEcoServiceServer(s grpc.ServiceRegistrar, srv EcoServiceServer) {
	s.RegisterService(&EcoService_ServiceDesc, srv)
}

func _EcoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.v1.EcoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcoServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EcoService_ServiceDesc is the grpc.ServiceDesc for EcoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.v1.EcoService",
	HandlerType: (*EcoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EcoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo/v1/echo.proto",
}
